apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    name: ""
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  source:
    path: apps/core-apps/sealed-secrets
    repoURL: "https://github.com/LuaKT/argocd-test.git"
    targetRevision: master
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
