apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    FOO: AgBE+2sY85dkfmsA+obAI2YkPsoS/ip1dIgZvxBFWcg2le+6Fxogn0eCsL4onj5kCoBBEtd1ATZmKfpIelA6xSMG0HVYEXQ5eiCKoT8sFX1e/Y7543SEsOquARKs2Qm/4JyyoP6ZFUJtTnNHQSp7/O1ESP6mneHbDkpaJkUMhr78cSf2qu6V2EBIxKS5aqKrr6Xorb2ENbaTrY2WalftemMqSrFMocFjRnB7tvF+fNP9V4vvF6NAw/SdYr4FtF9rmuA4RhD///jNI/sl2l192SjnovyVbchPL/4fYXKwAcPkALdhnylkkFQaEut6795N5TBQugGgi0YZkPB/vKtcndCJEem+V3bONqY55bYl+DNld3fkFWvPyA4YFAHvyuhE/XZsv8e4n0dQ9z3HtlmaCFOElUX9CTF1QUs2cq1MpD+xoyosusuvYj+VEhpRXuAP6lV7kgBbDF3m53vcjP+D8s2TWrpM05tMTlErT1FIB/uZpYDmzm9x4BVbYpDTd+Luyj894gVUGwC3L6F3MdrA2b0smAdh8xRRdHMtYo2NNFrQ436GmywP4q5UkuLOGiRcXSoQg2wQJbYHidZJm3kW+PBNwl9UpfqEszuUqx0xUJmOOMrZPXh29KP+FBUea3kqyV4PvWuO3eXU9jVMgh3EqJevXZIVRX0/5Vgcox2bAO+4Zjc6FTsG+m7+I+25oRr9wzYYC9o=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

